#ifndef DEFINES_H
#define DEFINES_H

//General defines
#define BLINK_TIME					500
#define BLINK_ERROR_TIME			200
#define MAX_VOLTAGE					96
#define OP_VOLTAGE					92
#define ST_VOLTAGE					86
#define MIN_V_CELL					1000
#define MAX_V_CELL					1000
#define N_OF_PACKS					6
#define N_OF_SLAVES					9
#define N_OF_CELLS					13
#define N_OF_THERMISTORS			4
#define MAX_CELL_V_DISCHARGE		36000//36500
#define MAX_CELL_V_CHARGE			36000
#define MAX_CELL_V_STORE			33000/
#define MIN_CELL_V					26000//27500
#define MIN_CELL_V_BALLANCE 		23000
#define FUSE_LIMIT					1
#define V_ERROR_COM					65528
#define MAX_TEMPERATURE				59000
#define T_ERROR_COM					1
#define BALANCE_TIME				120
#define BALANCE_V_ERROR				5

//Logical defines
#define FALSE 	0
#define TRUE 	1

//Ports defines
#define __DLC__ 8
#define DEBUG_Pin GPIO_PIN_13
#define DEBUG_GPIO_Port GPIOC
#define OSCI_Pin GPIO_PIN_0
#define OSCI_GPIO_Port GPIOD
#define OSCO_Pin GPIO_PIN_1
#define OSCO_GPIO_Port GPIOD
#define CURRENT2_200_Pin GPIO_PIN_0
#define CURRENT2_200_GPIO_Port GPIOA
#define CURRENT2_25_Pin GPIO_PIN_1
#define CURRENT2_25_GPIO_Port GPIOA
#define CURRENT1_200_Pin GPIO_PIN_2
#define CURRENT1_200_GPIO_Port GPIOA
#define CURRENT1_25_Pin GPIO_PIN_3
#define CURRENT1_25_GPIO_Port GPIOA
#define ISOSPI_CS_Pin GPIO_PIN_4
#define ISOSPI_CS_GPIO_Port GPIOA
#define ISOSPI_SCK_Pin GPIO_PIN_5
#define ISOSPI_SCK_GPIO_Port GPIOA
#define ISOSPI_MISO_Pin GPIO_PIN_6
#define ISOSPI_MISO_GPIO_Port GPIOA
#define ISOSPI_MOSI_Pin GPIO_PIN_7
#define ISOSPI_MOSI_GPIO_Port GPIOA
#define GLV_SAMPLE_Pin GPIO_PIN_1
#define GLV_SAMPLE_GPIO_Port GPIOB
#define MODE_SELECT_Pin GPIO_PIN_8
#define MODE_SELECT_GPIO_Port GPIOA
#define MODE_SELECT_EXTI_IRQn EXTI9_5_IRQn
#define FLAG_RESET_Pin GPIO_PIN_10
#define FLAG_RESET_GPIO_Port GPIOA
#define FLAG_RESET_EXTI_IRQn EXTI15_10_IRQn
#define AIR_ENABLE_Pin GPIO_PIN_3
#define AIR_ENABLE_GPIO_Port GPIOB
#define CHARGE_ENABLE_Pin GPIO_PIN_4
#define CHARGE_ENABLE_GPIO_Port GPIOB
#define ERR_LED_Pin GPIO_PIN_7
#define ERR_LED_GPIO_Port GPIOB
#define AIR_AUX_PLUS_Pin GPIO_PIN_8
#define AIR_AUX_PLUS_GPIO_Port GPIOB
#define AIR_AUX_MINUS_Pin GPIO_PIN_9
#define AIR_AUX_MINUS_GPIO_Port GPIOB

#endif
