#ifndef DEFINES_H
#define DEFINES_H

//Logical defines
#define FALSE 	0
#define TRUE 	1

//Ports defines
#define __DLC__ 8
#define DEBUG_Pin GPIO_PIN_13
#define DEBUG_GPIO_Port GPIOC
#define OSCI_Pin GPIO_PIN_0
#define OSCI_GPIO_Port GPIOD
#define OSCO_Pin GPIO_PIN_1
#define OSCO_GPIO_Port GPIOD
#define CURRENT2_200_Pin GPIO_PIN_0
#define CURRENT2_200_GPIO_Port GPIOA
#define CURRENT2_25_Pin GPIO_PIN_1
#define CURRENT2_25_GPIO_Port GPIOA
#define CURRENT1_200_Pin GPIO_PIN_2
#define CURRENT1_200_GPIO_Port GPIOA
#define CURRENT1_25_Pin GPIO_PIN_3
#define CURRENT1_25_GPIO_Port GPIOA
#define ISOSPI_CS_Pin GPIO_PIN_4
#define ISOSPI_CS_GPIO_Port GPIOA
#define ISOSPI_SCK_Pin GPIO_PIN_5
#define ISOSPI_SCK_GPIO_Port GPIOA
#define ISOSPI_MISO_Pin GPIO_PIN_6
#define ISOSPI_MISO_GPIO_Port GPIOA
#define ISOSPI_MOSI_Pin GPIO_PIN_7
#define ISOSPI_MOSI_GPIO_Port GPIOA
#define GLV_SAMPLE_Pin GPIO_PIN_1
#define GLV_SAMPLE_GPIO_Port GPIOB
#define MODE_SELECT_Pin GPIO_PIN_8
#define MODE_SELECT_GPIO_Port GPIOA
#define MODE_SELECT_EXTI_IRQn EXTI9_5_IRQn
#define FLAG_RESET_Pin GPIO_PIN_10
#define FLAG_RESET_GPIO_Port GPIOA
#define FLAG_RESET_EXTI_IRQn EXTI15_10_IRQn
#define AIR_ENABLE_Pin GPIO_PIN_3
#define AIR_ENABLE_GPIO_Port GPIOB
#define CHARGE_ENABLE_Pin GPIO_PIN_4
#define CHARGE_ENABLE_GPIO_Port GPIOB
#define ERR_LED_Pin GPIO_PIN_7
#define ERR_LED_GPIO_Port GPIOB
#define AIR_AUX_PLUS_Pin GPIO_PIN_8
#define AIR_AUX_PLUS_GPIO_Port GPIOB
#define AIR_AUX_MINUS_Pin GPIO_PIN_9
#define AIR_AUX_MINUS_GPIO_Port GPIOB

#endif
